Lampa.Lang.addCodes({pt:'Português'});

Lampa.Lang.AddTranslation('pt',{ lang_choice_title: 'Bem-vindo',
    lang_choice_subtitle: 'Escolha seu idioma',
    more: 'Mais',
    show_more: 'Mostrar mais',
    more_results: 'Mostrar mais resultados',
    loading: 'Carregando',
    nofind_movie: 'Não foi possível encontrar o filme.',
    noname: 'Sem título',
    nochoice: 'Não escolhido',
    cancel: 'Cancelar',
    confirm: 'Eu confirmo',
    sure: 'Tem a certeza?',
    nodata: 'Sem informação',
    search: 'Procurar',
    search_input: 'Digitar texto',
    search_empty: 'O histórico de pesquisa está vazio.',
    search_delete: 'Esquerda - Apagar',
    search_start_typing: 'Comece a digitar o texto de pesquisa.',
    search_searching: 'Pesquisa em andamento...',
    search_start: 'Começar a pesquisar',
    full_genre: 'Gênero',
    full_production: 'Produção',
    full_date_of_release: 'Data de lançamento',
    full_budget: 'Orçamento',
    full_countries: 'Países',
    full_like: 'Gosto',
    full_torrents: 'Torrents',
    full_trailers: 'Trailers',
    full_detail: 'Em detalhe',
    full_notext: 'Sem descrição.',
    full_series_release: 'Lançamento da série',
    full_next_episode: 'Seguinte',
    full_episode_days_left: 'Dias restantes',
    full_trailer_official: 'Oficial',
    full_trailer_no_official: 'Informal',
    full_season: 'Temporada',
    full_episode: 'Episódio',
    full_directing: 'Direção',
    settings_cub_sync: 'Sincronização',
    settings_cub_sync_descr: 'Sincronização com o serviço CUB: Sincronize os seus favoritos, histórico de navegação, tags e tempo de execução. Website: https://cub.watch',
    settings_cub_account: 'Conta',
    settings_cub_logged_in_as: 'Logado como',
    settings_cub_profile: 'Perfil',
    settings_cub_sync_btn: 'Sincronizar',
    settings_cub_sync_btn_descr: 'Guardar marcadores locais na conta CUB',
    settings_cub_backup: 'Backup',
    settings_cub_backup_descr: 'Guardar ou carregar backup',
    settings_cub_logout: 'Sair',
    settings_cub_signin: 'Autorização',
    settings_cub_not_specified: 'Não específicado',
    settings_cub_password: 'Password',
    settings_cub_status: 'Estado',
    settings_cub_backup_import: 'Importar',
    settings_cub_backup_export: 'Exportar',
    settings_input_links: 'Favoritos',
    settings_interface_type: 'Versão Lite',
    settings_interface_size: 'Tamanho da interface',
    settings_interface_background: 'Fundo',
    settings_interface_background_use: 'Mostrar fundo',
    settings_interface_background_type: 'Tipo de fundo',
    settings_interface_performance: 'Performance',
    settings_interface_animation: 'Animação',
    settings_interface_animation_descr: 'Animação dos posters e conteúdo',
    settings_interface_attenuation: 'Atenuação',
    settings_interface_attenuation_descr: 'Desvanecimento suave dos posters de baixo e de cima',
    settings_interface_scroll: 'Tipo de scroll',
    settings_interface_view_card: 'Tipo de visualização do poster',
    settings_interface_view_card_descr: 'Conforme rolar o feed, os posters serão carregados gradualmente ou carregarão todos',
    settings_interface_lang: 'Idioma da interface',
    settings_interface_lang_reload: 'É necessário reiniciar a aplicação, clique em "OK" para reiniciar.',
    settings_main_account: 'Conta',
    settings_main_interface: 'Interface',
    settings_main_player: 'Leitor',
    settings_main_parser: 'Analisador',
    settings_main_torrserver: 'TorrServer',
    settings_main_plugins: 'Plugins',
    settings_main_rest: 'Outros',
    settings_rest_start: 'Página inicial',
    settings_rest_start_descr: 'Qual página para iniciar na inicialização',
    settings_rest_source: 'Fonte',
    settings_rest_source_use: 'Fonte principal',
    settings_rest_source_descr: 'Obter informações sobre filmes',
    settings_rest_tmdb_lang: 'Idioma TMDB',
    settings_rest_tmdb_prox: 'Proxy TMDB',
    settings_rest_tmdb_posters: 'Resolução dos posters TMDB',
    settings_rest_screensaver: 'Proteção de ecrã',
    settings_rest_screensaver_use: 'Mostrar tela inicial quando ocupado',
    settings_rest_screensaver_type: 'Tipo proteção de ecrã',
    settings_rest_helper: 'Dicas',
    settings_rest_helper_use: 'Mostrar dicas',
    settings_rest_helper_reset: 'Mostrar dicas novamente',
    settings_rest_pages: 'Quantas páginas manter na memória',
    settings_rest_pages_descr: 'Manter as páginas no estado em deixei',
    settings_rest_time: 'Shift time',
    settings_rest_navigation: 'Tipo navegação',
    settings_rest_keyboard: 'Tipo teclado',
    settings_rest_device: 'Nome do dispositivo',
    settings_rest_device_placeholder: 'Exemplo: Meu Lampa',
    settings_rest_cache: 'Limpar cache',
    settings_rest_cache_descr: 'Todas as configurações e dados serão eliminados',
    settings_parser_use: 'Usar analisador',
    settings_parser_use_descr: 'Por este meio, você concorda em aceitar toda a responsabilidade pelo uso de links públicos para visualizar torrents e conteúdo online.',
    settings_parser_type: 'Tipo de analisador para torrents',
    settings_parser_jackett_placeholder: 'Por exemplo: 192.168.x',
    settings_parser_jackett_link: 'Endereço',
    settings_parser_jackett_link_descr: 'Forneça um link para o Jackett',
    settings_parser_jackett_key_placeholder: 'Por exemplo: sa0sk83d..',
    settings_parser_jackett_key: 'Api key',
    settings_parser_jackett_key_descr: 'Localizado em Jackett',
    settings_parser_torlook_type: 'Método de análise do site TorLook',
    settings_parser_scraperapi_placeholder: 'Por exemplo: scraperapi.com',
    settings_parser_scraperapi_link: 'Link para o analisador',
    settings_parser_scraperapi_descr: 'Registe-se no site scraperapi.com, entre no link api.scraperapi.com?api_key=...&url={q}<br>W41.torlook.info será entregue a {q}',
    settings_parser_search: 'Procurar',
    settings_parser_search_descr: 'Em que idioma deseja pesquisar?',
    settings_parser_in_search: 'Analisador a pesquisar',
    settings_parser_in_search_descr: 'Mostrar resultados da pesquisa?',
    settings_player_type: 'Tipo do leitor',
    settings_player_type_descr: 'Escolha o leitor',
    settings_player_reset: 'Redefinir leitor padrão',
    settings_player_reset_descr: 'Redefine o leitor Android selecionado na aplicação',
    settings_player_path: 'Caminho do leitor',
    settings_player_path_descr: 'Específique o caminho para o leitor (.exe)',
    settings_player_normalization: 'Normalização do Som',
    settings_player_normalization_descr: 'Normaliza o som para um nível, reduz os sons altos e aumenta os sons baixos.',
    settings_player_next_episode: 'Episódio seguinte',
    settings_player_next_episode_descr: 'Mudar automaticamente para o próximo episódio',
    settings_player_timecode: 'Tempo visualizado',
    settings_player_timecode_descr: 'Continuar do último tempo visualizado',
    settings_player_scale: 'Método de dimensionamento',
    settings_player_scale_descr: 'Como calcular o dimensionamento de vídeo',
    settings_player_subs: 'Legendas',
    settings_player_subs_use: 'Ligada',
    settings_player_subs_use_descr: 'Ativar sempre as legendas depois de iniciar o vídeo',
    settings_player_subs_size: 'Tamanho',
    settings_player_subs_size_descr: 'Tamanho das legendas',
    settings_player_subs_stroke_use: 'Usar contorno',
    settings_player_subs_stroke_use_descr: 'As legendas serão contornadas em preto para melhor legibilidade',
    settings_player_subs_backdrop_use: 'Usar fundo',
    settings_player_subs_backdrop_use_descr: 'As legendas serão exibidas em um fundo translúcido para melhorar a legibilidade',
    settings_player_quality: 'Qualidade de vídeo (padrão)',
    settings_player_quality_descr: 'Qualidade de vídeo preferida para visualização',
    settings_plugins_notice: 'Para aplicar o plugin, você precisa reiniciar a aplicação',
    settings_plugins_add: 'Adicionar Plugin',
    settings_plugins_add_descr: 'Para eliminar um plugin, segure ou clique duas vezes na tecla (OK) nele',
    settings_plugins_install: 'Instalar Plugin',
    settings_plugins_install_descr: 'Instale um plugin da lista de disponíveis',
    settings_server_link: 'Usar endereço',
    settings_server_links: 'Endereços',
    settings_server_placeholder: 'Por exemplo: 192.168.X',
    settings_server_link_one: 'Endereço principal',
    settings_server_link_one_descr: 'Especifique o endereço principal para o TorrServer',
    settings_server_link_two: 'Endereço adicional',
    settings_server_link_two_descr: 'Especifique o endereço adicional para o TorrServer',
    settings_server_additionally: 'Adicionalmente',
    settings_server_client: 'Embedded client',
    settings_server_client_descr: 'Use the built-in TorrServe JS client, otherwise the system one starts.',
    settings_server_base: 'Save to database',
    settings_server_base_descr: 'The torrent will be added to the TorrServer database',
    settings_server_preload: 'Use prefetch buffer',
    settings_server_preload_descr: 'Wait for TorrServer\'s preload buffer to fill before playing',
    settings_server_auth: 'Authorization',
    settings_server_password_use: 'Password login',
    settings_server_login: 'Login',
    settings_server_password: 'Password',
    settings_server_not_specified: 'Not specified',
    torent_nohash_reasons: 'The reasons',
    torent_nohash_reason_one: 'TorServer was unable to download the torrent file',
    torent_nohash_reason_two: 'Reply from TorServer',
    torent_nohash_reason_three: 'Link',
    torent_nohash_do: 'What to do?',
    torent_nohash_do_one: 'Check if you configured Jackett correctly',
    torent_nohash_do_two: 'Private sources may not provide a link to the file',
    torent_nohash_do_three: 'Make sure Jackett can download the file too',
    torent_nohash_do_four: 'Write to our telegram group: @lampa_group',
    torent_nohash_do_five: 'Specify which movie, which distribution and, if possible, a photo of this distribution',
    torrent_error_text: 'Failed to connect to TorrServe. Let\'s quickly go through the list of possible problems and check everything.',
    torrent_error_step_1: 'Is TorrServe running',
    torrent_error_step_2: 'Dynamic IP',
    torrent_error_step_3: 'Protocol and Port',
    torrent_error_step_4: 'Antivirus blocking',
    torrent_error_step_5: 'Check for availability',
    torrent_error_step_6: 'Still doesn\'t work',
    torrent_error_info_1: 'Make sure you have launched TorrServe on the device where it is installed.',
    torrent_error_info_2: 'A common mistake, the IP address of the device with TorrServe has changed. Make sure that the IP address you entered - {ip} - matches the address of the device on which TorrServe is installed.',
    torrent_error_info_3: 'To connect to TorrServe, you must specify the protocol http:// at the beginning and port :8090 at the end of the address. Make sure there is a port after the IP address, your current address is {ip}',
    torrent_error_info_4: 'Frequent occurrence, antivirus or firewall can block access by IP address, try disabling antivirus and firewall.',
    torrent_error_info_5: 'On any other device on the same network, open the {ip} address in a browser and check if the TorrServe web interface is available.',
    torrent_error_info_6: 'If, after all the checks, a connection error still occurs, try restarting TorrServe and the Internet adapter.',
    torrent_error_info_7: 'If the problem persists, write to the Telegram group @lampa_group with the text (Lampa does not connect to TorrServe after all checks, the current address is {ip})',
    torrent_error_start: 'Start verification',
    torrent_error_nomatrix: 'Failed to verify Matrix version',
    torrent_error_made: 'Performed',
    torrent_error_from: 'from',
    torrent_error_next: 'Further',
    torrent_error_complite: 'To complete',
    torrent_error_connect: 'Connection error',
    torrent_install_need: 'Requires TorrServe',
    torrent_install_text: 'TorrServe is an application that allows you to view content from torrent files online.<br><br>More detailed information on installation can be found in the Telegram groups below.',
    torrent_install_contact: 'Telegram groups',
    torrent_item_bitrate: 'Bitrate',
    torrent_item_seeds: 'Handing out',
    torrent_item_grabs: 'pumping',
    torrent_item_mb: 'Mbps',
    torrent_serial_episode: 'Series',
    torrent_serial_season: 'Season',
    torrent_serial_date: 'Exit',
    torrent_get_magnet: 'Requesting a magnet link',
    torrent_remove_title: 'Delete',
    torrent_remove_descr: 'The torrent will be removed from your list',
    torrent_parser_any_one: 'Any',
    torrent_parser_any_two: 'Any',
    torrent_parser_no_choice: 'Not chosen',
    torrent_parser_yes: 'Yes',
    torrent_parser_no: 'No',
    torrent_parser_quality: 'Quality',
    torrent_parser_subs: 'Subtitles',
    torrent_parser_voice: 'Translation',
    torrent_parser_tracker: 'tracker',
    torrent_parser_year: 'Year',
    torrent_parser_season: 'Season',
    torrent_parser_sort_by_seeders: 'By distributors',
    torrent_parser_sort_by_size: 'To size',
    torrent_parser_sort_by_name: 'by name',
    torrent_parser_sort_by_tracker: 'By source',
    torrent_parser_sort_by_date: 'By date',
    torrent_parser_sort_by_viewed: 'Viewed',
    torrent_parser_voice_dubbing: 'Dubbing',
    torrent_parser_voice_polyphonic: 'Polyphonic',
    torrent_parser_voice_two: 'Two-voiced',
    torrent_parser_voice_amateur: 'Amateur',
    torrent_parser_reset: 'Reset filter',
    torrent_parser_empty: 'Failed to get results',
    torrent_parser_no_hash: 'Failed to get HASH',
    torrent_parser_added_to_mytorrents: 'added to "My torrents"',
    torrent_parser_add_to_mytorrents: 'Add to "My torrents"',
    torrent_parser_label_title: 'Flag',
    torrent_parser_label_descr: 'Flag a hand with a flag (viewed)',
    torrent_parser_label_cancel_title: 'Uncheck',
    torrent_parser_label_cancel_descr: 'Remove the mark from the distribution (viewed)',
    torrent_parser_timeout: 'Timeout expired',
    torrent_parser_nofiles: 'Failed to extract suitable files',
    torrent_parser_set_link: 'Specify a link for parsing',
    torrent_parser_request_error: 'Request error',
    torrent_parser_magnet_error: 'Failed to get magnet link',
    about_text: 'The application is completely free and uses public links to get information about videos, new releases, popular movies, etc. All available information is used solely for educational purposes, the application does not use its own servers to distribute information.',
    about_channel: 'Nosso canal',
    about_group: 'Grupo',
    about_version: 'Versão',
    about_donate: 'Donativos',
    title_watched: 'You watched',
    title_settings: 'Definições',
    title_collections: 'Coleções',
    title_collections_ivi: 'Coleções no IVI',
    title_collections_okko: 'Coleções no OKKO',
    title_company: 'Companhia',
    title_actors: 'Atores',
    title_actor: 'Ator',
    title_actress: 'Atriz',
    title_person: 'Pessoas',
    title_comments: 'Comentários',
    title_torrents: 'Torrents',
    title_trailers: 'Trailers',
    title_watch: 'Ver',
    title_error: 'Erro',
    title_links: 'Endereços',
    title_choice: 'Escolher',
    title_main: 'Início',
    title_book: 'Favoritos',
    title_like: 'Gosto',
    title_wath: 'Ver mais tarde',
    title_history: 'Histórico de navegação',
    title_mytorrents: 'Meus torrents',
    title_last: 'Último',
    title_action: 'Ação',
    title_producer: 'Produtor',
    title_collection: 'Coleção',
    title_recomendations: 'Recomendações',
    title_similar: 'Similares',
    title_about: 'Sobre a aplicação',
    title_timetable: 'Calendário',
    title_relises: 'Lançamento digital',
    title_catalog: 'Catálogo',
    title_category: 'Categoria',
    title_parser: 'Analisador',
    title_type: 'Tipo de',
    title_rating: 'Classificação',
    title_country: 'País',
    title_year: 'Ano',
    title_genre: 'Gênero',
    title_filter: 'Filtro',
    title_notice: 'Notificações',
    title_files: 'Ficheiros',
    title_now_watch: 'Assistindo agora',
    title_latest: 'Última adição',
    title_continue: 'Continuar navegando',
    title_recomend_watch: 'Recomendamos ver',
    title_new_episodes: 'Novos episódios',
    title_popular: 'Popular',
    title_popular_movie: 'Filmes populares',
    title_popular_tv: 'Séries populares',
    title_new_this_year: 'Novidades do ano',
    title_hight_voite: 'Classificações altas',
    title_new: 'Novo',
    title_trend_day: 'Tendências de hoje',
    title_trend_week: 'Tendências da semana',
    title_upcoming: 'Nos cinemas',
    title_top_movie: 'Top filmes',
    title_top_tv: 'Top séries',
    title_tv_today: 'No ar hoje',
    title_this_week: 'Esta semana',
    title_in_top: 'Top',
    title_out: 'Sair',
    title_out_confirm: 'Sim, quero sair',
    title_continue_two: 'Proceder',
    company_headquarters: 'Headquarters',
    company_homepage: 'Website',
    company_country: 'País',
    filter_clarify: 'Clarificar',
    filter_clarify_two: 'Refinar procura',
    filter_set_name: 'Especificar título',
    filter_sorted: 'Ordenar',
    filter_filtred: 'Filtro',
    filter_any: 'Algum',
    filter_rating_from: 'a partir de',
    filter_rating_to: 'até',
    filter_country_uk: 'Ucrânia',
    filter_country_en: 'EUA',
    filter_country_ru: 'Rússia',
    filter_country_ja: 'Japão',
    filter_country_ko: 'Corea',
    filter_country_az: 'Azerbeijão',
    filter_country_sq: 'Albânia',
    filter_country_be: 'Bielorrússia',
    filter_country_bg: 'Bulgária',
    filter_country_de: 'Alemanha',
    filter_country_ka: 'Geórgia',
    filter_country_da: 'Dinamarca',
    filter_country_et: 'Estónia',
    filter_country_ga: 'Irlanda',
    filter_country_es: 'Espanha',
    filter_country_it: 'Itália',
    filter_country_zh: 'China',
    filter_country_lv: 'Letónia',
    filter_country_ne: 'Nepal',
    filter_country_no: 'Noruega',
    filter_country_pl: 'Polónia',
    filter_country_ro: 'Roménia',
    filter_country_sr: 'Sérvia',
    filter_country_sk: 'Eslováquia',
    filter_country_sl: 'Eslovénia',
    filter_country_tg: 'Tajiquistão',
    filter_country_tr: 'Turquia',
    filter_country_uz: 'Uzbequistão',
    filter_country_fi: 'Finlândia',
    filter_country_fr: 'França',
    filter_country_hr: 'Croácia',
    filter_country_cs: 'República Checa',
    filter_country_sv: 'Suécia',
    filter_genre_ac: 'Ação',
    filter_genre_ad: 'Aventura',
    filter_genre_mv: 'Desenho animado',
    filter_genre_cm: 'Comédia',
    filter_genre_cr: 'Crime',
    filter_genre_dc: 'Documentário',
    filter_genre_dr: 'Drama',
    filter_genre_fm: 'Família',
    filter_genre_fe: 'Fantasia',
    filter_genre_hi: 'História',
    filter_genre_ho: 'Horror',
    filter_genre_mu: 'Musical',
    filter_genre_de: 'Detetive',
    filter_genre_md: 'Melodrama',
    filter_genre_fa: 'Ficção',
    filter_genre_tv: 'Telefilme',
    filter_genre_tr: 'Thriller',
    filter_genre_mi: 'Militar',
    filter_genre_ve: 'Western',
    filter_genre_aa: 'Ação e Aventura',
    filter_genre_ch: 'Infantil',
    filter_genre_nw: 'Novos',
    filter_genre_rs: 'Reality show',
    filter_genre_hf: 'Ficção Científica e Fantasia',
    filter_genre_op: 'Novela',
    filter_genre_tc: 'Talk show',
    filter_genre_mp: 'Guerra e política',
    ivi_premieres: 'Movie premieres',
    ivi_best: 'Best Movies',
    ivi_popular: 'Popular now',
    ivi_choice: 'Ivi\'s choice',
    ivi_new: 'New',
    ivi_foreign: 'Foreign',
    ivi_ru: 'Russians',
    ivi_recomend: 'We recommend that you see',
    ivi_for_famaly: 'Cartoons for the whole family',
    ivi_triller: 'Horror thrillers',
    ivi_advance: 'Adventure comedies',
    ivi_detective: 'Film adaptations of detectives',
    ivi_crime_comedy: 'Crime comedies',
    ivi_romantic: 'Romantic dramas',
    ivi_crime_dramas: 'Crime dramas',
    ivi_fantastic_dramas: 'fantasy dramas',
    ivi_military_dramas: 'Military dramas',
    ivi_mistic: 'Mystery films',
    ivi_foreign_series: 'Foreign series',
    ivi_historical_series: 'Historical series',
    okko_top_new: 'Top New',
    okko_comedy_horror: 'Comedy Horror Films',
    okko_collection_maniacs: 'Movies about maniacs',
    okko_witches: 'Movies about witches',
    okko_zombies: 'Movies about zombies',
    okko_ru: 'Russians',
    okko_horror_serial: 'Very scary',
    okko_serial_killers: 'About maniacs',
    okko_humor_serial: 'With black humor',
    okko_legkiye_serialy: 'Lungs',
    okko_comedy_serial: 'Comedy',
    okko_ru_tv: 'Russians',
    empty_title: 'Empty',
    empty_text: 'Nothing found for your filter, please refine your filter.',
    empty_title_two: 'It\'s empty here',
    empty_text_two: 'The list is currently empty.',
    menu_main: 'Início',
    menu_movies: 'Filmes',
    menu_tv: 'Séries',
    menu_catalog: 'Catálogo',
    menu_filter: 'Filtro',
    menu_collections: 'Coleções',
    menu_relises: 'Novidades',
    menu_anime: 'Anime',
    menu_bookmark: 'Favoritos',
    menu_like: 'Gosto',
    menu_time: 'Ver mais tarde',
    menu_history: 'Histórico',
    menu_timeline: 'Calendário',
    menu_torrents: 'Torrents',
    menu_settings: 'Definições',
    menu_about: 'Sobre',
    menu_console: 'Consola',
    menu_multmovie: 'Cartoons',
    menu_multtv: 'Séries animadas',
    plugins_catalog_work: 'Working plugins',
    plugins_catalog_work_descr: 'Plugins that work exactly in the lamp.',
    plugins_catalog_popular: 'Popular plugins among users',
    plugins_catalog_popular_descr: 'Installation from unknown sources may cause the application to work incorrectly.',
    plugins_online: 'View online',
    plugins_check_fail: 'Failed to test the functionality of the plugin. However, this does not mean that the plugin does not work. Reload the application to see if the plugin is loading.',
    plugins_need_reload: 'To apply the plugin, you need to restart the application',
    plugins_install: 'Install',
    plugins_install_ready: 'This plugin is already installed.',
    plugins_installed: 'Installations',
    plugins_load_from: 'Loaded from CUB',
    plugins_ok_for_check: 'Click (OK) to test the plugin',
    plugins_no_loaded: 'When loading the application, some plugins could not be loaded',
    time_viewed: 'Viewed',
    time_from: 'from',
    time_reset: 'Reset timecode',
    settings_clear_cache: 'Cache and data cleared',
    settings_user_links: 'Custom Link',
    settings_for_local: 'For local TorrServer',
    settings_add: 'Add',
    settings_remove: 'Delete',
    settings_this_value: 'present value',
    settings_added: 'Added',
    settings_removed: 'Removed',
    settings_param_player_inner: 'Lampa',
    settings_param_player_outside: 'External',
    settings_param_yes: 'Yes',
    settings_param_no: 'No',
    settings_param_interface_size_small: 'Smaller',
    settings_param_interface_size_normal: 'Normal',
    settings_param_poster_quality_low: 'Low',
    settings_param_poster_quality_average: 'Average',
    settings_param_poster_quality_high: 'High',
    settings_param_parse_directly: 'Directly',
    settings_param_parse_api: 'Through the website API',
    settings_param_background_complex: 'Complex',
    settings_param_background_simple: 'Simple',
    settings_param_background_image: 'Picture',
    settings_param_link_use_one: 'Main',
    settings_param_link_use_two: 'Additional',
    settings_param_subtitles_size_small: 'small',
    settings_param_subtitles_size_normal: 'Ordinary',
    settings_param_subtitles_size_bigger: 'Large',
    settings_param_screensaver_nature: 'Nature',
    settings_param_lang_ru: 'Русский',
    settings_param_lang_uk: 'Українська',
    settings_param_lang_en: 'English',
	settings_param_lang_pt: 'Português',
    settings_param_torrent_lang_orig: 'Original',
    settings_param_torrent_lang_ru: 'Russian',
    settings_param_player_timecode_again: 'Start over',
    settings_param_player_timecode_continue: 'Proceed',
    settings_param_player_timecode_ask: 'To ask',
    settings_param_player_scale_method: 'Calculate',
    settings_param_card_view_load: 'Upload',
    settings_param_card_view_all: 'Show all',
    settings_param_navigation_remote: 'Remote controller',
    settings_param_navigation_mouse: 'Remote control with mouse',
    settings_param_keyboard_lampa: 'Lampa',
    settings_param_keyboard_system: 'Systemic',
    helper_keyboard: 'After entering the value, press the "Back" button to save',
    helper_torrents: 'Hold down the (OK) key to bring up the context menu',
    helper_cleared: 'Success, tooltips will be shown again.',
    helper_torrents_view: 'Hold down the (OK) key to reset the timecode and display the menu',
    fav_sync_title: 'Bookmark sync',
    fav_sync_text: 'Do you want your favorite bookmarks to be on all your devices? <br><br>Register on the site www.cub.watch, create a profile and log in to the lamp.',
    fav_sync_site: 'Website',
    fav_remove_title: 'Remove from history',
    fav_remove_descr: 'Delete selected card',
    fav_clear_title: 'Clear the history',
    fav_clear_descr: 'Delete all cards from history',
    fav_clear_label_title: 'Clear labels',
    fav_clear_label_descr: 'Clear View Tags',
    fav_clear_time_title: 'Clear Timecodes',
    fav_clear_time_descr: 'Clear all timecodes',
    fav_label_cleared: 'Marks cleared',
    fav_time_cleared: 'Timecodes cleared',
    timetable_empty: 'This section will display the release dates of new episodes.',
    player_quality: 'Quality',
    player_tracks: 'Audio tracks',
    player_disabled: 'Disabled',
    player_unknown: 'Unknown',
    player_subs: 'Subtitles',
    player_size_default_title: 'Default',
    player_size_default_descr: 'Default video size',
    player_size_cover_title: 'Expand',
    player_size_cover_descr: 'Expands video to full screen',
    player_size_fill_title: 'Fill',
    player_size_fill_descr: 'Fit video to full screen',
    player_size_s115_title: 'Zoom 115%',
    player_size_s115_descr: 'Enlarge video by 115%',
    player_size_s130_title: 'Zoom 130%',
    player_size_s130_descr: 'Enlarge video by 130%',
    player_size_v115_title: 'Vertical 115%',
    player_size_v115_descr: 'Enlarge video by 115%',
    player_size_v130_title: 'Vertical 130%',
    player_size_v130_descr: 'Enlarge video by 130%',
    player_video_size: 'Video size',
    player_playlist: 'Playlist',
    player_error_one: 'Failed to decode video',
    player_error_two: 'Video not found or corrupted',
    player_start_from: 'Continue browsing from',
    player_not_found: 'Player not found',
    player_lauch: 'Launch player',
    broadcast_open: 'Open card on another device',
    broadcast_play: 'Choose the device to watch on',
    card_new_episode: 'New series',
    card_book_remove: 'Remove from bookmarks',
    card_book_add: 'To bookmarks',
    card_book_descr: 'Look in the menu (Bookmarks)',
    card_like_remove: 'Remove from favorites',
    card_like_add: 'Like',
    card_like_descr: 'Look at the menu (Like)',
    card_wath_remove: 'Remove from expected',
    card_wath_add: 'Watch Later',
    card_wath_descr: 'See the menu (Later)',
    card_history_remove: 'Remove from history',
    card_history_add: 'Add to history',
    card_history_descr: 'Look in the menu (History)',
    keyboard_listen: 'Speak, I\'m listening...',
    keyboard_nomic: 'No microphone access',
    notice_new_quality: 'New quality available',
    notice_quality: 'Quality',
    notice_new_episode: 'New series',
    notice_none: 'You don\'t have any notifications yet, register at <b>www.cub.watch</b> to follow new episodes and releases.',
    notice_in_quality: 'As',
    copy_link: 'Copy video link',
    copy_secuses: 'Link copied to clipboard',
    copy_error: 'Error copying link',
    account_sync_to_profile: 'All bookmarks will be moved to the profile',
    account_sync_secuses: 'All bookmarks have been successfully transferred',
    account_profiles: 'Profiles',
    account_profiles_empty: 'Failed to get list of profiles',
    account_authorized: 'Authorized',
    account_logged_in: 'You are logged in',
    account_login_failed: 'Login failed',
    account_login_wait: 'Waiting for login',
    account_profile_main: 'General',
    account_export_secuses: 'Export completed successfully',
    account_export_fail: 'Export error',
    account_import_secuses: 'Import completed successfully',
    account_import_fail: 'Import error',
    account_imported: 'imported',
    account_reload_after: 'reboot after 5 sec.',
    network_noconnect: 'No network connection',
    network_404: 'The requested page was not found. [404]',
    network_401: 'Authorization failed',
    network_500: 'Internal Server Error. [500]',
    network_parsererror: 'The requested JSON parsing failed.',
    network_timeout: 'Request timed out.',
    network_abort: 'The request has been aborted.',
    network_error: 'Erro desconhecido',
    size_zero: '0 Byte',
    size_byte: 'Byte',
    size_kb: 'KB',
    size_mb: 'MB',
    size_gb: 'GB',
    size_tb: 'TB',
    size_pp: 'PB',
    speed_bit: 'bit',
    speed_kb: 'Kbps',
    speed_mb: 'Mbps',
    speed_gb: 'Gbit',
    speed_tb: 'Tbit',
    speed_pp: 'Pbit',
    month_1: 'Janeiro',
    month_2: 'Fevereiro',
    month_3: 'Março',
    month_4: 'Abril',
    month_5: 'Maio',
    month_6: 'Junho',
    month_7: 'Julho',
    month_8: 'Agosto',
    month_9: 'Setembro',
    month_10: 'Outubro',
    month_11: 'Novembro',
    month_12: 'Dezembro',
    day_1: 'Segunda',
    day_2: 'Terça',
    day_3: 'Quarta',
    day_4: 'Quinta',
    day_5: 'Sexta',
    day_6: 'Sábado',
    day_7: 'Domingo',
    month_1_e: 'Jan',
    month_2_e: 'Fev',
    month_3_e: 'Mar',
    month_4_e: 'Abr',
    month_5_e: 'Mai',
    month_6_e: 'Jun',
    month_7_e: 'Jul',
    month_8_e: 'Ago',
    month_9_e: 'Set',
    month_10_e: 'Out',
    month_11_e: 'Nov',
    month_12_e: 'Dez',
    week_1: 'Seg',
    week_2: 'Ter',
    week_3: 'Qua',
    week_4: 'Qui',
    week_5: 'Sex',
    week_6: 'Sáb',
    week_7: 'Dom',
    settings_param_player_hls_app: 'Sistema',
    settings_param_player_hls_js: 'Programa',
    settings_player_hls_title: 'Processing the .m3u8 stream',
    settings_player_hls_descr: 'Do not touch this parameter if you do not know why it is.',
    notice_none_account: 'You don\'t have any notifications yet, bookmark the series and wait for notifications of new episodes.',
    player_speed_default_title: 'Plain',
    player_video_speed: 'Playback speed',
    player_share_title: 'Share',
    player_share_descr: 'Play this video on another device'
});
